// Generated by Xata Codegen 0.30.1. Please do not edit.
import type { BaseClientOptions, SchemaInference } from "@xata.io/client";
import { buildClient } from "@xata.io/client";

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://kishan-talekar-s-workspace-i2rf18.us-east-1.xata.sh/db/snapcast",
  apiKey: process.env.XATA_API_KEY,
  branch: "main",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
